os:
  - osx
  - linux
language: generic
sudo: required
dist: trusty
osx_image: xcode8
install:
  - source ./Scripts/Travis/install-swift.sh
script:
  - ./Scripts/Travis/build-test.sh
after_success:
  - ./Scripts/Travis/report-coverage.sh
